export const getAttackMultiplicatorAndMessage = (type1, type2) => {
  let multiplicator;
  let message;
  // Si un des modificateurs est = 0, donc si un des deux types du défenseur est immunisé à l'attaque, alors ça touche pas
  if (type1 === 0 || type2 === 0) {
    multiplicator = 0;
    message = 'Aucun effet...';
  }
  // En cas de double faiblesse
  else if (type1 === 2 && type2 === 2) {
    multiplicator = 4;
    message = 'C\'est vraiment super efficace !';
  }
  // En cas de double résistance
  else if (type1 === 0.5 && type2 === 0.5) {
    multiplicator = 0.25;
    message = 'Ce n\'est vraiment pas très efficace';
  }
  // En cas de faiblesse et résistance simultanées, on pourrait faire if( ($modifType1 == 2 AND $modifType2 == 0.5) OR ($modifType1 == 0.5 AND $modifType2 == 2) )
  // Mais on peut aussi vérifier que le modificateur est égal a 2.5 (2+0.5). Dans les deux cas, on applique les dégats normaux
  else if (type1 + type2 === 2.5) {
    multiplicator = 1;
    message = '';
  }
  // En cas de simple résistance, à partir de la, pas besoin de vérifier le deuxième type, il sera toujours égal à 1 d'après les conditions précédentes
  else if (type1 === 0.5 || type2 === 0.5) {
    multiplicator = 0.5;
    message = 'Ce n\'est pas très efficace !';
  }
  // En cas de simple faiblesse
  else if (type1 === 2 || type2 === 2) {
    multiplicator = 2;
    message = 'C\'est super efficace !';
  }
  // Quand il n'y a pas de modificateur particulier
  else {
    multiplicator = 1;
    message = '';
  }



  return {multiplicator, message};
};

export const affinityTable = {
  'Acier': {
    'Acier'    : 0.5,
    'Combat'   : 1,
    'Dragon'   : 1,
    'Eau'      : 0.5,
    'Electrik' : 0.5,
    'Fée'      : 2,
    'Feu'      : 0.5,
    'Glace'    : 2,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 1,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 2,
    'Sol'      : 1,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 1,
  },
  'Combat': {
    'Acier'    : 2,
    'Combat'   : 1,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 0.5,
    'Feu'      : 1,
    'Glace'    : 2,
    'Insecte'  : 0.5,
    'Normal'   : 2,
    'Plante'   : 1,
    'Poison'   : 0.5,
    'Psy'      : 0.5,
    'Roche'    : 2,
    'Sol'      : 1,   
    'Spectre'  : 0,
    'Tenebres' : 2,
    'Vol'      : 0.5,
  },
  'Dragon': {
    'Acier'    : 0.5,
    'Combat'   : 1,
    'Dragon'   : 2,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 0,
    'Feu'      : 1,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 1,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 1,
    'Sol'      : 1,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 1,
  },
  'Eau': {
    'Acier'    : 1,
    'Combat'   : 1,
    'Dragon'   : 0.5,
    'Eau'      : 0.5,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 2,
    'Glace'    : 0,
    'Insecte'  : 0,
    'Normal'   : 0,
    'Plante'   : 0.5,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 2,
    'Sol'      : 2,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 1,
  },
  'Electrik': {
    'Acier'    : 1,
    'Combat'   : 1,
    'Dragon'   : 0.5,
    'Eau'      : 2,
    'Electrik' : 0.5,
    'Fée'      : 1,
    'Feu'      : 1,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 0.5,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 1,
    'Sol'      : 0,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 2,
  },
  'Fée': {
    'Acier'    : 0.5,
    'Combat'   : 2,
    'Dragon'   : 2,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 0.5,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 1,
    'Poison'   : 0.5,
    'Psy'      : 1,
    'Roche'    : 1,
    'Sol'      : 1,   
    'Spectre'  : 1,
    'Tenebres' : 2,
    'Vol'      : 1,
  },
  'Feu': {
    'Acier'    : 2,
    'Combat'   : 1,
    'Dragon'   : 0.5,
    'Eau'      : 0.5,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 0.5,
    'Glace'    : 2,
    'Insecte'  : 2,
    'Normal'   : 1,
    'Plante'   : 2,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 0.5,
    'Sol'      : 1,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 1,
  },
  'Glace': {
    'Acier'    : 0.5,
    'Combat'   : 1,
    'Dragon'   : 2,
    'Eau'      : 0.5,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 0.5,
    'Glace'    : 0.5,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 2,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 1,
    'Sol'      : 2,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 2,
  },
  'Insecte': {
    'Acier'    : 0.5,
    'Combat'   : 0.5,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 0.5,
    'Feu'      : 0.5,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 2,
    'Poison'   : 0.5,
    'Psy'      : 2,
    'Roche'    : 1,
    'Sol'      : 1,   
    'Spectre'  : 0.5,
    'Tenebres' : 2,
    'Vol'      : 0.5,
  },
  'Normal': {
    'Acier'    : 0.5,
    'Combat'   : 1,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 1,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 1,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 0.5,
    'Sol'      : 1,   
    'Spectre'  : 0,
    'Tenebres' : 1,
    'Vol'      : 1,
  },
  'Plante': {
    'Acier'    : 0.5,
    'Combat'   : 1,
    'Dragon'   : 0.5,
    'Eau'      : 2,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 0.5,
    'Glace'    : 1,
    'Insecte'  : 0.5,
    'Normal'   : 1,
    'Plante'   : 0.5,
    'Poison'   : 0.5,
    'Psy'      : 1,
    'Roche'    : 2,
    'Sol'      : 2,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 0.5,
  },
  'Poison': {
    'Acier'    : 0,
    'Combat'   : 1,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 2,
    'Feu'      : 1,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 2,
    'Poison'   : 0.5,
    'Psy'      : 1,
    'Roche'    : 0.5,
    'Sol'      : 0.5,  
    'Spectre'  : 0.5,
    'Tenebres' : 1,
    'Vol'      : 1,
  },
  'Psy': {
    'Acier'    : 0.5,
    'Combat'   : 2,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 1,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 1,
    'Poison'   : 2,
    'Psy'      : 0.5,
    'Roche'    : 1,
    'Sol'      : 1,   
    'Spectre'  : 1,
    'Tenebres' : 0,
    'Vol'      : 1,
  },
  'Roche': {
    'Acier'    : 0.5,
    'Combat'   : 0.5,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 2,
    'Glace'    : 2,
    'Insecte'  : 2,
    'Normal'   : 1,
    'Plante'   : 1,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 1,
    'Sol'      : 0.5,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 2,
  },
  'Sol': {
    'Acier'    : 2,
    'Combat'   : 1,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 2,
    'Fée'      : 1,
    'Feu'      : 2,
    'Glace'    : 1,
    'Insecte'  : 0.5,
    'Normal'   : 1,
    'Plante'   : 0.5,
    'Poison'   : 2,
    'Psy'      : 1,
    'Roche'    : 2,
    'Sol'      : 1,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 0,
  },
  'Spectre': {
    'Acier'    : 1,
    'Combat'   : 1,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 1,
    'Feu'      : 1,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 0,
    'Plante'   : 1,
    'Poison'   : 1,
    'Psy'      : 2,
    'Roche'    : 1,
    'Sol'      : 1,   
    'Spectre'  : 2,
    'Tenebres' : 0.5,
    'Vol'      : 1,
  },
  'Tenebres': {
    'Acier'    : 1,
    'Combat'   : 0.5,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 1,
    'Fée'      : 0.5,
    'Feu'      : 1,
    'Glace'    : 1,
    'Insecte'  : 1,
    'Normal'   : 1,
    'Plante'   : 1,
    'Poison'   : 1,
    'Psy'      : 2,
    'Roche'    : 1,
    'Sol'      : 1,   
    'Spectre'  : 2,
    'Tenebres' : 0.5,
    'Vol'      : 1,
  },
  'Vol': {
    'Acier'    : 0.5,
    'Combat'   : 2,
    'Dragon'   : 1,
    'Eau'      : 1,
    'Electrik' : 0.5,
    'Fée'      : 1,
    'Feu'      : 1,
    'Glace'    : 1,
    'Insecte'  : 2,
    'Normal'   : 1,
    'Plante'   : 2,
    'Poison'   : 1,
    'Psy'      : 1,
    'Roche'    : 0.5,
    'Sol'      : 1,   
    'Spectre'  : 1,
    'Tenebres' : 1,
    'Vol'      : 1,
  },
};
