<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPNdFHLD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPNdFHLD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPNdFHLD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPNdFHLD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPNdFHLD\App_KernelDevDebugContainer([
    'container.build_hash' => 'PNdFHLD',
    'container.build_id' => 'c40d69c7',
    'container.build_time' => 1583317490,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPNdFHLD');
