<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVfYHGxT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVfYHGxT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVfYHGxT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVfYHGxT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVfYHGxT\App_KernelDevDebugContainer([
    'container.build_hash' => 'VfYHGxT',
    'container.build_id' => '12c53a5d',
    'container.build_time' => 1583318961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVfYHGxT');
