<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2w7V2vP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2w7V2vP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2w7V2vP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2w7V2vP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2w7V2vP\App_KernelDevDebugContainer([
    'container.build_hash' => '2w7V2vP',
    'container.build_id' => '17f79463',
    'container.build_time' => 1582811863,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2w7V2vP');
